# Generated by Django 5.0.2 on 2024-02-08 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_time_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time_purchased',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 15, 10, 651470)),
        ),
    ]
